version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: team_todo
      MYSQL_USER: lego
      MYSQL_PASSWORD: lego
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u lego --password=lego"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build: ./php
    container_name: php_container
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - .:/var/www/html
    depends_on:
      php:
        condition: service_started

volumes:
  db_data:
