version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    networks:
      - app-network

  todo-service:
    build: ./todo-service
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend-service:
    build: ./frontend-service
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
