apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: ttd
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"  # 실제 데이터가 저장될 경로