apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ttd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: zox2m/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-files
          mountPath: /var/www/html
        resources: 
          requests:
            cpu: "100m"
            memory: 128Mi
          limits:
            cpu: "500m"
            memory: 256Mi
      volumes:
      - name: web-files
        configMap:
          name: web-files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: ttd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php-container
        image: zox2m/php:8.2
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: web-files
          mountPath: /var/www/html
      volumes:
      - name: web-files
        configMap:
          name: web-files
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: ttd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: zox2m/mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: team_todo
        - name: MYSQL_USER
          value: lego
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
