apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: ttd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx-container
          image: zox2m/nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-files
              mountPath: /var/www/html
        - name: php-container
          image: zox2m/php:8.2
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: web-files
              mountPath: /var/www/html
      volumes:
        - name: web-files
          configMap:
            name: web-files
