apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ttd
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # base64 인코딩된 'root'
  MYSQL_PASSWORD: bGVnbw==      # base64 인코딩된 'lego'
