apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ttd
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root   /var/www/html;
            index  index.html index.htm;
        }

        location ~ \.php$ {
            root           /var/www/html;
            fastcgi_pass   php-service:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
  namespace: ttd
data:
  index.php: |
    <?php
    phpinfo();
    ?>
