FROM mysql:8.0

# 환경 변수 설정
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=team_todo
ENV MYSQL_USER=lego
ENV MYSQL_PASSWORD=lego

# 복사하는 SQL 스크립트
COPY . /docker-entrypoint-initdb.d/
COPY ./my.cnf /etc/mysql/mysql.conf.d/


# 기본 MySQL entrypoint를 유지하면서 초기화 스크립트를 실행하는 CMD 설정
CMD ["mysqld"]
