name: 메인 브랜치 푸시 시 배포하기

on:
  push:
    branches:
      - new_main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v2

      - name: Docker Hub에 로그인
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: kubectl 설정하기
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > ${{ github.workspace }}/kubeconfig.yaml

      - name: Nginx Docker 이미지 빌드 및 푸시
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/nginx:latest ./nginx
          docker push zox2m/nginx:latest
          kubectl apply -f k8s/ttd-deploy.yaml -n ttd

      - name: PHP Docker 이미지 빌드 및 푸시
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/php:8.2 ./php
          docker push zox2m/php:8.2
          kubectl apply -f k8s/ttd-deploy.yaml -n ttd

      - name: MySQL Docker 이미지 빌드 및 푸시
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/mysql:8.0 ./sql
          docker push zox2m/mysql:8.0
          kubectl apply -f k8s/ttd-deploy.yaml -n ttd
