name: Deploy on Main Branch Push

on:
  push:
    branches:
      - new_main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Nginx Docker Image
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/nginx:latest ./nginx
          docker push zox2m/nginx:latest

      - name: Set up Kubernetes environment variables
        env:
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
          KUBE_CA: ${{ secrets.KUBE_CA }}
        run: |
          kubectl config set-cluster my-cluster --server=$KUBE_SERVER --certificate-authority=<(echo "$KUBE_CA") --embed-certs=true
          kubectl config set-credentials my-user --token=$KUBE_TOKEN
          kubectl config set-context my-context --cluster=my-cluster --user=my-user
          kubectl config use-context my-context

      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/new_main'
        run: |
          kubectl apply -f k8s/ttd-deploy.yaml -n ttd
