name: Deploy on Main Branch Push

on:
  push:
    branches:
      - new_main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Nginx Docker Image
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/nginx:latest ./nginx
          docker push zox2m/nginx:latest
          kubectl rollout restart deployment/nginx-deployment -n ttd

      - name: Build and Push PHP Docker Image
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/php:8.2 ./php
          docker push zox2m/php:8.2
          kubectl rollout restart deployment/php-deployment -n ttd

      - name: Build and Push MySQL Docker Image
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/mysql:8.0 ./sql
          docker push zox2m/mysql:8.0
          kubectl rollout restart deployment/mysql-deployment -n ttd
