name: Deploy on Main Branch Push

on:
  push:
    branches:
      - new_main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Nginx Docker Image
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/nginx:latest ./nginx
          docker push zox2m/nginx:latest

      - name: Build and Push PHP Docker Image
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/php:8.2 ./php
          docker push zox2m/php:8.2

      - name: Build and Push MySQL Docker Image
        if: github.ref == 'refs/heads/new_main'
        run: |
          docker build -t zox2m/mysql:8.0 ./sql
          docker push zox2m/mysql:8.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.21.0'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          kubectl config set-context --current --namespace=default

      - name: Update Kubernetes Deployment
        if: github.ref == 'refs/heads/new_main'
        run: |
          kubectl apply -f k8s/ttd-deploy.yaml -n ttd
